apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-deployment
  namespace: projectcontour
  labels:
    app: app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
        - name: app4
          image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/app4:851b51ca7122ffd171cffe6ffa460d550294d6f9
          ports:
            - containerPort: 3004
