apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app4-proxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: app4.swa-raj.online
    tls:
      secretName: app4-cert-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: app4-service
          port: 80
