apiVersion: apps/v1
kind: Deployment
metadata:
  name: app6-deployment
  namespace: projectcontour
  labels:
    app: app6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app6
  template:
    metadata:
      labels:
        app: app6
    spec:
      containers:
        - name: app6
          image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/app6:24c60296bc14a583e33f376beb23071230b29f9c
          imagePullPolicy: Always
          ports:
            - containerPort: 30006
