apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app6-certificate
  namespace: projectcontour
spec:
  commonName: app6.swa-raj.online
  dnsNames:
    - app6.swa-raj.online
  issuerRef:
    kind: ClusterIssuer
    name: app6-clusterissuer  
  secretName: app6-cert-tls  