apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app6-proxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: app6.swa-raj.online
  routes:
    - conditions:
        - prefix: /
      services:
        - name: app6-service
          port: 80