apiVersion: apps/v1
kind: Deployment
metadata:
  name: app6-deployment
  namespace: projectcontour
  labels:
    app: app6
spec:
  selector:
    matchLabels:
      app: app6
  template:
    metadata:
      labels:
        app: app6
    spec:
      containers:
        - name: app6
          image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/app6:30f645eb97b1f1fb20d403422ebcbe66fce7927b
          imagePullPolicy: Always
          ports:
            - containerPort: 30006
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
