apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app3-proxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: app3.swa-raj.online
  routes:
    - conditions:
        - prefix: /
      services:
        - name: app3-service
          port: 80