apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  namespace: projectcontour
  labels:
    app: app3
spec:
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/app3:23e7b2af968dda68c021ec4d5076eb4bed2fad0c
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
