apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: projectcontour
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/snaveed1/app1:7ef5430970aef51f34ca01a0a80566b20ec5fc4d
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
