apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app1-certificate
  namespace: projectcontour
spec:
  commonName: app1.swa-raj.online
  dnsNames:
    - app1.swa-raj.online
  issuerRef:
    kind: ClusterIssuer
    name: app1-clusterissuer  
  secretName: app1-cert-tls  