apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app1-proxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: app1.swa-raj.online
    tls:
      secretName: app1-cert-tls 
  routes:
    - conditions:
        - prefix: /
      services:
        - name: app1-service
          port: 80
