apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: app2-proxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: app2.swa-raj.online
    tls:
      secretName: app2-cert-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: app2-service
          port: 80
