apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: projectcontour
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: us-central1-docker.pkg.dev/naveed-project-438207/apps-images/snaveed1/app2:app2
        imagePullPolicy: Always
        ports:
        - containerPort: 3002