apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: app2-clusterissuer 
  namespace: cert-manager 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shaikhnaved10346@gmail.com  
    privateKeySecretRef:
      name: app2-clusterissuer
    solvers:
      - http01:
          ingress:
            class: contour  